# 389. Find The Difference

# You are given 2 strings 's' and 't'.
# String 't' is generated by random shuffling 's' and then add one more letter at a random position.
# Return the letter that was added to 't'.

# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e": Explanation: 'e' is the letter that was added.

# Example 2:
# Input: s = "", t = "y"
# Output: "y"

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        # calculate numeric ascii value for each char in s
        s_sum = 0
        t_sum = 0
        for i in s:
            s_sum += ord(i)
        
        # calculate numeric ascii value for each char in t
        for j in t:
            t_sum += ord(j)

        # calculate the difference between both string
        sum = t_sum - s_sum

        # convert back to character
        return chr(sum)
    
if __name__ == "__main__":
    solution = Solution()
    print(solution.findTheDifference("saya","sayas"))